// QuranData.js

const surahNames = [
    { english: "Al-Fatiha", arabic: "الفاتحة" },
    { english: "Al-Baqarah", arabic: "البقرة" },
    { english: "Al-Imran", arabic: "آل عمران" },
    { english: "An-Nisa", arabic: "النساء" },
    { english: "Al-Ma'idah", arabic: "المائدة" },
    { english: "Al-An'am", arabic: "الأنعام" },
    { english: "Al-A'raf", arabic: "الأعراف" },
    { english: "Al-Anfal", arabic: "الأنفال" },
    { english: "At-Tawbah", arabic: "التوبة" },
    { english: "Yunus", arabic: "يونس" },
    { english: "Hud", arabic: "هود" },
    { english: "Yusuf", arabic: "يوسف" },
    { english: "Ar-Ra'd", arabic: "الرعد" },
    { english: "Ibrahim", arabic: "إبراهيم" },
    { english: "Al-Hijr", arabic: "الحجر" },
    { english: "An-Nahl", arabic: "النحل" },
    { english: "Al-Isra", arabic: "الإسراء" },
    { english: "Al-Kahf", arabic: "الكهف" },
    { english: "Maryam", arabic: "مريم" },
    { english: "Taha", arabic: "طه" },
    { english: "Al-Anbiya", arabic: "الأنبياء" },
    { english: "Al-Hajj", arabic: "الحج" },
    { english: "Al-Mu'minun", arabic: "المؤمنون" },
    { english: "An-Nur", arabic: "النور" },
    { english: "Al-Furqan", arabic: "الفرقان" },
    { english: "Ash-Shu'ara", arabic: "الشعراء" },
    { english: "An-Naml", arabic: "النمل" },
    { english: "Al-Qasas", arabic: "القصص" },
    { english: "Al-Ankabut", arabic: "العنكبوت" },
    { english: "Ar-Rum", arabic: "الروم" },
    { english: "Luqman", arabic: "لقمان" },
    { english: "As-Sajda", arabic: "السجدة" },
    { english: "Al-Ahzab", arabic: "الأحزاب" },
    { english: "Saba", arabic: "سبأ" },
    { english: "Fatir", arabic: "فاطر" },
    { english: "Ya-Sin", arabic: "يس" },
    { english: "As-Saffat", arabic: "الصافات" },
    { english: "Sad", arabic: "ص" },
    { english: "Az-Zumar", arabic: "الزمر" },
    { english: "Ghafir", arabic: "غافر" },
    { english: "Fussilat", arabic: "فصلت" },
    { english: "Ash-Shura", arabic: "الشورى" },
    { english: "Az-Zukhruf", arabic: "الزخرف" },
    { english: "Ad-Dukhan", arabic: "الدخان" },
    { english: "Al-Jathiya", arabic: "الجاثية" },
    { english: "Al-Ahqaf", arabic: "الأحقاف" },
    { english: "Muhammad", arabic: "محمد" },
    { english: "Al-Fath", arabic: "الفتح" },
    { english: "Al-Hujurat", arabic: "الحجرات" },
    { english: "Qaf", arabic: "ق" },
    { english: "Adh-Dhariyat", arabic: "الذاريات" },
    { english: "At-Tur", arabic: "الطور" },
    { english: "An-Najm", arabic: "النجم" },
    { english: "Al-Qamar", arabic: "القمر" },
    { english: "Ar-Rahman", arabic: "الرحمن" },
    { english: "Al-Waqi'a", arabic: "الواقعة" },
    { english: "Al-Hadid", arabic: "الحديد" },
    { english: "Al-Mujadila", arabic: "المجادلة" },
    { english: "Al-Hashr", arabic: "الحشر" },
    { english: "Al-Mumtahina", arabic: "الممتحنة" },
    { english: "As-Saff", arabic: "الصف" },
    { english: "Al-Jumua", arabic: "الجمعة" },
    { english: "Al-Munafiqun", arabic: "المنافقون" },
    { english: "At-Taghabun", arabic: "التغابن" },
    { english: "At-Talaq", arabic: "الطلاق" },
    { english: "At-Tahrim", arabic: "التحريم" },
    { english: "Al-Mulk", arabic: "الملك" },
    { english: "Al-Qalam", arabic: "القلم" },
    { english: "Al-Haqqah", arabic: "الحاقة" },
    { english: "Al-Ma'arij", arabic: "المعارج" },
    { english: "Nuh", arabic: "نوح" },
    { english: "Al-Jinn", arabic: "الجن" },
    { english: "Al-Muzzammil", arabic: "المزمل" },
    { english: "Al-Muddathir", arabic: "المدثر" },
    { english: "Al-Qiyama", arabic: "القيامة" },
    { english: "Al-Insan", arabic: "الإنسان" },
    { english: "Al-Mursalat", arabic: "المرسلات" },
    { english: "An-Naba", arabic: "النبأ" },
    { english: "An-Nazi'at", arabic: "النازعات" },
    { english: "Abasa", arabic: "عبس" },
    { english: "At-Takwir", arabic: "التكوير" },
    { english: "Al-Infitar", arabic: "الإنفطار" },
    { english: "Al-Mutaffifin", arabic: "المطففين" },
    { english: "Al-Inshiqaq", arabic: "الإنشقاق" },
    { english: "Al-Buruj", arabic: "البروج" },
    { english: "At-Tariq", arabic: "الطارق" },
    { english: "Al-A'la", arabic: "الأعلى" },
    { english: "Al-Ghashiya", arabic: "الغاشية" },
    { english: "Al-Fajr", arabic: "الفجر" },
    { english: "Al-Balad", arabic: "البلد" },
    { english: "Ash-Shams", arabic: "الشمس" },
    { english: "Al-Lail", arabic: "الليل" },
    { english: "Ad-Duha", arabic: "الضحى" },
    { english: "Ash-Sharh", arabic: "الشرح" },
    { english: "At-Tin", arabic: "التين" },
    { english: "Al-'Alaq", arabic: "العلق" },
    { english: "Al-Qadr", arabic: "القدر" },
    { english: "Al-Bayyina", arabic: "البينة" },
    { english: "Az-Zalzala", arabic:"الزلزل "},
    { english: "Al-Adiyat", arabic: "العاديات" },
  { english: "Al-Qaria", arabic: "القارعة" },
  { english: "At-Takathur", arabic: "التكاثر" },
  { english: "Al-Asr", arabic: "العصر" },
  { english: "Al-Humaza", arabic: "الهمزة" },
  { english: "Al-Fil", arabic: "الفيل" },
  { english: "Quraish", arabic: "قريش" },
  { english: "Al-Ma'un", arabic: "الماعون" },
  { english: "Al-Kawthar", arabic: "الكوثر" },
  { english: "Al-Kafirun", arabic: "الكافرون" },
  { english: "An-Nasr", arabic: "النصر" },
  { english: "Al-Masad", arabic: "المسد" },
  { english: "Al-Ikhlas", arabic: "الإخلاص" },
  { english: "Al-Falaq", arabic: "الفلق" },
  { english: "An-Nas", arabic: "الناس" }
];

const surahDetails = [
    { number: 1, name: "Al-Fatiha", verses: 7, revelationType: "Meccan" },
{ number: 2, name: "Al-Baqarah", verses: 286, revelationType: "Medinan" },
{ number: 3, name: "Al Imran", verses: 200, revelationType: "Medinan" },
{ number: 4, name: "An-Nisa", verses: 176, revelationType: "Medinan" },
{ number: 5, name: "Al-Maidah", verses: 120, revelationType: "Medinan" },
{ number: 6, name: "Al-An'am", verses: 165, revelationType: "Meccan" },
{ number: 7, name: "Al-A'raf", verses: 206, revelationType: "Meccan" },
{ number: 8, name: "Al-Anfal", verses: 75, revelationType: "Medinan" },
{ number: 9, name: "At-Tawbah", verses: 129, revelationType: "Medinan" },
{ number: 10, name: "Yunus", verses: 109, revelationType: "Meccan" },
{ number: 11, name: "Hud", verses: 123, revelationType: "Meccan" },
{ number: 12, name: "Yusuf", verses: 111, revelationType: "Meccan" },
{ number: 13, name: "Ar-Ra'd", verses: 43, revelationType: "Meccan" },
{ number: 14, name: "Ibrahim", verses: 52, revelationType: "Meccan" },
{ number: 15, name: "Al-Hijr", verses: 99, revelationType: "Meccan" },
{ number: 16, name: "An-Nahl", verses: 128, revelationType: "Meccan" },
{ number: 17, name: "Al-Isra", verses: 111, revelationType: "Meccan" },
{ number: 18, name: "Al-Kahf", verses: 110, revelationType: "Meccan" },
{ number: 19, name: "Maryam", verses: 98, revelationType: "Meccan" },
{ number: 20, name: "Ta-Ha", verses: 135, revelationType: "Meccan" },
{ number: 21, name: "Al-Anbiya", verses: 112, revelationType: "Meccan" },
{ number: 22, name: "Al-Hajj", verses: 78, revelationType: "Medinan" },
{ number: 23, name: "Al-Mu'minun", verses: 118, revelationType: "Meccan" },
{ number: 24, name: "An-Nur", verses: 64, revelationType: "Medinan" },
{ number: 25, name: "Al-Furqan", verses: 70, revelationType: "Meccan" },
{ number: 26, name: "Ash-Shu'ara", verses: 227, revelationType: "Meccan" },
{ number: 27, name: "An-Naml", verses: 93, revelationType: "Meccan" },
{ number: 28, name: "Al-Qasas", verses: 88, revelationType: "Meccan" },
{ number: 29, name: "Al-'Ankabut", verses: 69, revelationType: "Meccan" },
{ number: 30, name: "Ar-Rum", verses: 60, revelationType: "Meccan" },
{ number: 31, name: "Luqman", verses: 34, revelationType: "Meccan" },
{ number: 32, name: "As-Sajdah", verses: 30, revelationType: "Meccan" },
{ number: 33, name: "Al-Ahzab", verses: 73, revelationType: "Medinan" },
{ number: 34, name: "Saba", verses: 54, revelationType: "Meccan" },
{ number: 35, name: "Fatir", verses: 45, revelationType: "Meccan" },
{ number: 36, name: "Ya-Sin", verses: 83, revelationType: "Meccan" },
{ number: 37, name: "As-Saffat", verses: 182, revelationType: "Meccan" },
{ number: 38, name: "Sad", verses: 88, revelationType: "Meccan" },
{ number: 39, name: "Az-Zumar", verses: 75, revelationType: "Meccan" },
{ number: 40, name: "Ghafir", verses: 85, revelationType: "Meccan" },
{ number: 41, name: "Fussilat", verses: 54, revelationType: "Meccan" },
{ number: 42, name: "Ash-Shura", verses: 53, revelationType: "Meccan" },
{ number: 43, name: "Az-Zukhruf", verses: 89, revelationType: "Meccan" },
{ number: 44, name: "Ad-Dukhan", verses: 59, revelationType: "Meccan" },
{ number: 45, name: "Al-Jathiyah", verses: 37, revelationType: "Meccan" },
{ number: 46, name: "Al-Ahqaf", verses: 35, revelationType: "Meccan" },
{ number: 47, name: "Muhammad", verses: 38, revelationType: "Medinan" },
{ number: 48, name: "Al-Fath", verses: 29, revelationType: "Medinan" },
{ number: 49, name: "Al-Hujurat", verses: 18, revelationType: "Medinan" },
{ number: 50, name: "Qaf", verses: 45, revelationType: "Meccan" },
{ number: 51, name: "Adh-Dhariyat", verses: 60, revelationType: "Meccan" },
{ number: 52, name: "At-Tur", verses: 49, revelationType: "Meccan" },
{ number: 53, name: "An-Najm", verses: 62, revelationType: "Meccan" },
{ number: 54, name: "Al-Qamar", verses: 55, revelationType: "Meccan" },
{ number: 55, name: "Ar-Rahman", verses: 78, revelationType: "Meccan" },
{ number: 56, name: "Al-Waqi'ah", verses: 96, revelationType: "Meccan" },
{ number: 57, name: "Al-Hadid", verses: 29, revelationType: "Medinan" },
{ number: 58, name: "Al-Mujadilah", verses: 22, revelationType: "Medinan" },
{ number: 59, name: "Al-Hashr", verses: 24, revelationType: "Medinan" },
{ number: 60, name: "Al-Mumtahanah", verses: 12, revelationType: "Medinan" },
{ number: 61, name: "As-Saff", verses: 14, revelationType: "Medinan" },
{ number: 62, name: "Al-Jumu'ah", verses: 11, revelationType: "Medinan" },
{ number: 63, name: "Al-Munafiqun", verses: 11, revelationType: "Medinan" },
{ number: 64, name: "At-Taghabun", verses: 18, revelationType: "Medinan" },
{ number: 65, name: "At-Talaq", verses: 12, revelationType: "Medinan" },
{ number: 66, name: "At-Tahrim", verses: 12, revelationType: "Medinan" },
{ number: 67, name: "Al-Mulk", verses: 30, revelationType: "Meccan" },
{ number: 68, name: "Al-Qalam", verses: 52, revelationType: "Meccan" },
{ number: 69, name: "Al-Haqqah", verses: 52, revelationType: "Meccan" },
{ number: 70, name: "Al-Ma'arij", verses: 44, revelationType: "Meccan" },
{ number: 71, name: "Nuh", verses: 28, revelationType: "Meccan" },
{ number: 72, name: "Al-Jinn", verses: 28, revelationType: "Meccan" },
{ number: 73, name: "Al-Muzzammil", verses: 20, revelationType: "Meccan" },
{ number: 74, name: "Al-Muddaththir", verses: 56, revelationType: "Meccan" },
{ number: 75, name: "Al-Qiyamah", verses: 40, revelationType: "Meccan" },
{ number: 76, name: "Al-Insan", verses: 31, revelationType: "Meccan" },
{ number: 77, name: "Al-Mursalat", verses: 50, revelationType: "Meccan" },
{ number: 78, name: "An-Naba", verses: 40, revelationType: "Meccan" },
{ number: 79, name: "An-Nazi'at", verses: 46, revelationType: "Meccan" },
{ number: 80, name: "'Abasa", verses: 42, revelationType: "Meccan" },
{ number: 81, name: "At-Takwir", verses: 29, revelationType: "Meccan" },
  { number: 82, name: "Al-Infitar", verses: 19, revelationType: "Meccan" },
  { number: 83, name: "Al-Mutaffifin", verses: 36, revelationType: "Meccan" },
  { number: 84, name: "Al-Inshiqaq", verses: 25, revelationType: "Meccan" },
  { number: 85, name: "Al-Buruj", verses: 22, revelationType: "Meccan" },
  { number: 86, name: "At-Tariq", verses: 17, revelationType: "Meccan" },
  { number: 87, name: "Al-A'la", verses: 19, revelationType: "Meccan" },
  { number: 88, name: "Al-Ghashiyah", verses: 26, revelationType: "Meccan" },
  { number: 89, name: "Al-Fajr", verses: 30, revelationType: "Meccan" },
  { number: 90, name: "Al-Balad", verses: 20, revelationType: "Meccan" },
  { number: 91, name: "Ash-Shams", verses: 15, revelationType: "Meccan" },
  { number: 92, name: "Al-Lail", verses: 21, revelationType: "Meccan" },
  { number: 93, name: "Ad-Duha", verses: 11, revelationType: "Meccan" },
  { number: 94, name: "Ash-Sharh", verses: 8, revelationType: "Meccan" },
  { number: 95, name: "At-Tin", verses: 8, revelationType: "Meccan" },
  { number: 96, name: "Al-'Alaq", verses: 19, revelationType: "Meccan" },
  { number: 97, name: "Al-Qadr", verses: 5, revelationType: "Meccan" },
  { number: 98, name: "Al-Bayyinah", verses: 8, revelationType: "Medinan" },
  { number: 99, name: "Az-Zalzalah", verses: 8, revelationType: "Medinan" },
  { number: 100, name: "Al-'Adiyat", verses: 11, revelationType: "Meccan" },
  { number: 100, name: "Al-Nahl", verses: 9 },
{ number: 101, name: "Al-Qariah", verses: 11 },
{ number: 102, name: "At-Takathur", verses: 8 },
{ number: 103, name: "Al-Asr", verses: 3 },
{ number: 104, name: "Al-Humazah", verses: 9 },
{ number: 105, name: "Al-Fil", verses: 5 },
{ number: 106, name: "Quraysh", verses: 4 },
{ number: 107, name: "Al-Ma'un", verses: 7 },
{ number: 108, name: "Al-Kawthar", verses: 3 },
{ number: 109, name: "Al-Kafirun", verses: 6 },
{ number: 110, name: "An-Nas", verses: 6 },
{ number: 111, name: "Al-Masad", verses: 5 },
{ number: 112, name: "Al-Ikhlas", verses: 4 },
{ number: 113, name: "Al-Falaq", verses: 5 },
{ number: 114, name: "An-Nas", verses: 6 }

];

export { surahNames,surahDetails };
